#数据源
spring:
  security:
    basic:
      enabled: flase
  datasource:
    platform: postgres
    url: jdbc:postgresql://10.12.6.169:5432/electricity?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: postgres
    password: guowushi
    driver-class-name: org.postgresql.Driver
    default-time-zone: +08:00
    character-set-server: utf8

# ====================MybatisPlus====================
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:mybatis/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.JZhi.project.entity
  global-config:
    #刷新mapper 调试神器
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: UUID
      #驼峰下划线转换
      column-underline: false
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
    refresh: true
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'
    # 打印sql语句和入参数据
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    database-id: mysql

# 日志配置
logging:
  level:
    org.springframework: warn

#加密配置
jasypt:
  encryptor:
    password: PWDSalt