task:
  # Socket配置
  socket:
    # 监听端口 2323
    port: 3000

  # 线程池参数
  pool:
    # 核心线程数 10
    core-pool-size: 10
    # 保持线程数 20
    keep-alive-seconds: 60
    # 最大线程数 int类型最大值
    max-pool-size: 0x7fffffff
    # 线程名前缀
    thread-name-prefix: clientTaskPool

  # 数据帧协议
  protocol:
    # 开始字符
    start: 43
    # 结束字符
    end: 16

  # MQTT
  mqtt:
    # MQTT 连接地址 如果有多个，用逗号隔开
    host: tcp://127.0.0.1:1883
    # 用户名
    username: guest
    # 密码
    password: guest
    # 默认主题
    topic: defaultTopic
    # clientId 唯一
    clientId: mqttProducer
    # 连接超时 单位：毫秒
    timeout: 3000
    # 心跳
    keepAlive: 60
    # 断线重连
    reconnect: true
